
This module only provides a path to the netCDF and HDF5 utilities (e.g. ncdump,
h5dump, ...) 

If you are compiling programs that require netcdf or hdf5 libraries, 1. load an
appropriate 
toolchain (e.g. buildenv-intel/2023a-eb), 2. load the corresponding netCDF-HDF5
module (e.g. 
netCDF-HDF5/4.9.2-1.12.2-hpc1).

***********************************
You have loaded a Mambaforge module
***********************************

JUST LOADING THIS MODULE DOES *NOT* CHANGE THE PYTHON VERSION, NOR ENABLES ANY
EXTRA PYTHON MODULES.

This module makes available the 'mamba' and 'conda' commands from the miniforge
Mambaforge distribution,
with which users can create named anaconda-like environments and then activate
them.

To create and use a customized environment use 'mamba create ...' and
then 'mamba activate ...' (see example below).

---------------------------------------------------------------------------------------------------
NOTE: NSC strongly advices against placing 'mamba activate' (or 'conda
activate', with or without
      arguments) in your shell initialization files, (e.g. '.bashrc' or
'.bash_profile') since
      this severly alters the environment for running software in ways that
cause unpredictable
      issues that can be difficult to diagnose.
---------------------------------------------------------------------------------------------------

Example usage:

  * Setting up a customized environment and run a Python program in it:

    mamba create -n myenv python=3.8 scipy=1.5.2
    mamba activate myenv
    python my_scipy_python_program.py

  * To run the python program in the same environment when logging in the next
time:

    mabma activate myenv
    python my_scipy_python_program.py

The miniforge Mambaforge distribution aims to be command-line compatible with
Anaconda.
More details on Anaconda environment management are available here:


https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html


+ cd /nobackup/rossby27/users/sm_yicwa/PROJECTS/01-PROJ_emulator/04-evaluation_fuxing/ClimulatorScore/src
+ python main.py -c /nobackup/rossby27/users/sm_yicwa/PROJECTS/01-PROJ_emulator/04-evaluation_fuxing/ClimulatorScore/config/config_EmiliaRomagna_Freja.yml
Traceback (most recent call last):
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
           ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
            ~~~~~~~~~~~^^^^^
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna/cropped/12km/6hr/mrsol/mrsol_12km_6hr_200001010000-200912311800.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '37b04799-9cae-448e-8ebe-fb2e1e5ff517']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nobackup/rossby27/users/sm_yicwa/PROJECTS/01-PROJ_emulator/04-evaluation_fuxing/ClimulatorScore/src/main.py", line 48, in <module>
    main()
    ~~~~^^
  File "/nobackup/rossby27/users/sm_yicwa/PROJECTS/01-PROJ_emulator/04-evaluation_fuxing/ClimulatorScore/src/main.py", line 32, in main
    get_data.get_data(experiment_files, var_name, unit_convert)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nobackup/rossby27/users/sm_yicwa/PROJECTS/01-PROJ_emulator/04-evaluation_fuxing/ClimulatorScore/src/get_data.py", line 24, in get_data
    ds = xr.open_dataset(file_name, decode_cf=False)
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/api.py", line 687, in open_dataset
    backend_ds = backend.open_dataset(
        filename_or_obj,
    ...<2 lines>...
        **kwargs,
    )
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/netCDF4_.py", line 666, in open_dataset
    store = NetCDF4DataStore.open(
        filename_or_obj,
    ...<8 lines>...
        autoclose=autoclose,
    )
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/netCDF4_.py", line 452, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/netCDF4_.py", line 393, in __init__
    self.format = self.ds.data_model
                  ^^^^^^^
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/netCDF4_.py", line 461, in ds
    return self._acquire()
           ~~~~~~~~~~~~~^^
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/netCDF4_.py", line 455, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/sm_yicwa/.conda/envs/climulatorscore/lib/python3.13/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2521, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2158, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: '/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna/cropped/12km/6hr/mrsol/mrsol_12km_6hr_200001010000-200912311800.nc'
